### PR TITLE
chat: fix chat input focus loss

### LINKED ISSUE #1729: chat: chat input loses focus after sending a message in group chat channels
OTT

### PR DESCRIPTION
**Pull request by patosullivan**
Fixes #1729 

It turns out this was caused by including `onReference` in the dependency array of the useCallback in handlePaste.

I also removed the useEffect we originally had in ChatInput for clearing text if no draft exists (didn't cause the issue we were seeing, but it was useless anyway and could cause other issues, I imagine).

### CODE REVIEW

**Comment by patosullivan** [comment]
this breaks chat blocks for refs on android. investigating further.

**Comment by patosullivan** [comment]
We're going to have to figure something else out for https://github.com/tloncorp/landscape-apps/issues/1679

For now I removed all reference logic from the handlePaste function.

File: ui/src/components/MessageEditor.tsx [hunk 1]
```diff
@@ -93,13 +93,6 @@ export function useMessageEditor({
       if (!whom) {
         return false;
       }
-      const text = event.clipboardData?.getData('text/plain');
-
-      if (text && isRef(text)) {
```
Comment (tomholford) [inline ui/src/components/MessageEditor.tsx:98]: If the pasted item is a ref, is it still handled as expected without this conditional branch?

**Review by tomholford — APPROVED** [review]
One question inline, otherwise LGTM

File: ui/src/components/MessageEditor.tsx (hunk 1 above)
Comment (patosullivan) [reply ui/src/components/MessageEditor.tsx:98]: Yes, this was just a way to force it since it wasn't happening using the existing method on Android.
