### PR TITLE
chat: reuse existing multi dms

### LINKED ISSUE #1704: New multiparty DM created for same recipients of prior multiparty DM
**Describe the bug, optionally with screenshots**
When using the flow to create a new multiparty DM a new multiparty DM is created every time even if there is an existing multiparty DM with the same participants.

**To Reproduce**
1. Select + New Message
2. Enter participants
3. FInish
4. New multiparty DM created

**Expected behavior**
Instead of creating a new DM each time, the existing one should be loaded.

### PR DESCRIPTION
**Pull request by arthyn**
This fixes #1704 ensuring that multi dms get recycled when available. Also included a fix for the cause of #1683, which is a rip out of the state nuking stuff since that really needs to go asap.

### CODE REVIEW

File: ui/src/dms/NewDm.tsx [hunk 1]
```diff
@@ -21,7 +22,29 @@ export default function NewDM() {
...
+      }
+
+      return key;
+    }, '');
+  }, [multiDms, shipValues]);
+  const who =
+    ships.length > 0
+      ? isMultiDm
+        ? existingMultiDm
+          ? existingMultiDm
```
Comment (tomholford) [inline ui/src/dms/NewDm.tsx:44]: Confirming this nested ternary checking for `existingMultiDm` in sequence is expected?

File: ui/src/state/chat/chat.ts [hunk 2]
```diff
@@ -900,7 +911,13 @@ export function useDmIsPending(ship: string) {
 
 const selMultiDms = (s: ChatState) => s.multiDms;
 export function useMultiDms() {
-  return useChatState(selMultiDms);
+  const dms = useChatState(selMultiDms);
+
+  useEffect(() => {
+    useChatState.getState().fetchMultiDms();
+  }, []);
```
Comment (tomholford) [inline ui/src/state/chat/chat.ts:918]: Confirming that multi DMs should be scried every time `NewDm` component is visited? Or is the initial subscription on application load sufficient?

**Review by tomholford — APPROVED** [review]
Grateful for the ☢️ removal! A couple questions inline, otherwise LGTM

File: ui/src/dms/NewDm.tsx (hunk 1 above)
Comment (arthyn) [reply ui/src/dms/NewDm.tsx:44]: Hmm this probably could be simplified

File: ui/src/state/chat/chat.ts (hunk 2 above)
Comment (arthyn) [reply ui/src/state/chat/chat.ts:918]: I didn't want to add another scry to our initial load and scrying every time someone visited new dm felt decent because it's pretty infrequent. We should probably revisit in another perf PR sometime soon.
