### PR TITLE
groups + talk: sidebar and mobile navigation restyling

### LINKED ISSUE #1186: groups: spacing between "sidebar sections" could use additional vertical height
The current implementation of our sidebar **section elements** omits some vertical spacing we've specified for increased legibility of the interface:

Screenshot 2022-11-17 at 12 16 39 PM

Under the last row in a given "section", the idea is to provide ~24px (or the tailwind spacing equivalent) of vertical margin/padding before the start of the next section:

Screenshot 2022-11-17 at 12 24 02 PM

### LINKED ISSUE #1190: groups/talk: Inter not rendering ligatures, perhaps more
**Describe the bug, optionally with screenshots**
It appears that opentype features such as automatic ligatures are not working with some people's groups/talk interfaces:

Screenshot 2022-11-17 at 1 24 38 PM

**To Reproduce**
1. Go into any groups/talk interface where text can be input + rendered 
2. Type in text representative of an automatic opentype feature (`->` is a good/easy example) and submit it 
3. If the arrow/opentype feature doesn't render properly/fancily, you've replicated the bug 

**Expected behavior**
I essentially expect the full breadth of opentype/typographic features available via Inter to "just work"

**Additional context:**
- Ship: planet (~tonlur-hidlyn)
- Instance type: Self-hosted (Digital Ocean)

Accessing the above urbit through the following machine, remotely:
- MacOS Ventura — 13.0.1 (22A400)
- Safari — Version 16.1 (18614.2.9.1.12)
- Chromium — Engine Version 106.0.5249.103

### LINKED ISSUE #1293: groups: update to sidebar nav "filter" and "sort" component
As we began to explore designs for the standalone notebook and collections apps, we realized that we were hitting some heavy limitations with our present "sort/filter" interface in the sidebar, so we've redesigned it.

Current Filter interface (dropdown selection emits from a row-button):

https://user-images.githubusercontent.com/1195363/204935067-1f39e391-dd35-4b7e-8cb7-6077ac1f19fa.mov

Proposed redesign (dropdown selection emits from an icon-button inlined with the separator label):

https://user-images.githubusercontent.com/1195363/204935110-8bdb4aa7-55f4-48cf-b4d9-b7ed692f2a62.mov

Effectively, this change amounts to moving the "filter/sort" function from the "Row"-like element into the "Separator" element as a right-aligned button, along with a potential "Search-Filter" function we'd like to add at some point.

We surmised this approach is beneficial for the following reasons:

1. This proposed location for the sort/filter button takes up less vertical space in the sidebar
2. The refactoring of the dropdown emanating from a button vs. a row clarifies the distinction between channel rows vs. the sort/filter function
3. The proposed location of the sort/filter button is a little more aligned with the _actual_ state of the separator label text, which changes depending on the currently selected sort. Inlining these two elements binds them closer together

### LINKED ISSUE #1603: Talk: in safari on iOS talk in landscape with all messages shows huge icons for dms
C8F9A27C-C745-456A-86C6-EC28780F35C7

### LINKED ISSUE #1746: groups: omnibus improvements to the sidebar component
This issue collects several usability-oriented updates for the Groups app sidebar:

1. Consolidation of the top-level "Group Actions Menu" and "Back to All Groups" interfaces into a single row (acting as an improved "anchor" for the whole sidebar)
2. Addition of a "Home" button, which will initially house notifications for an individual group in the style of an "Activity Feed", but will later become a more customizable "focal point/landing page" for a group (See: #1691)
3. Surfacing an admin-only "Create New Channel" button on the sidebar, for improved ease-of-discovery of the channel creation interface
4. Redesign of the "Channel Filter/Sort" interface, melding the dropdown button into the section-separator, and adding an explicit "search-like filter" for quick channel/group search (See: #1293)
5. Drag handle on the sidebar for sidebar resizing and total hiding, includes an associated keyboard shortcut

<details><summary>Visual Update Highlights (image)</summary>
Screenshot 2023-01-19 at 5 13 15 PM
</details>

Group with no Header:

https://user-images.githubusercontent.com/1195363/213588749-bd468b16-1b38-4023-8266-a9f72af4f90c.mov

Group with a Header:

https://user-images.githubusercontent.com/1195363/213591046-36c88380-4890-4bae-8e76-ebdfffb31620.mov

**Note**: This issue does not expect each improvement to be implemented at once, as each of the items above more or less exist as isolated components that can be updated one at a time, in any order. 

@jamesacklin Consider this issue a sort of "index" or "table of contents" in which I can address broader issues with the entire proposal, but ideally we can handle the actual implementation tasks of any individual update in a separate ticket.

As usual, designs can be found in Figma: 
https://www.figma.com/file/luXjuX8fdV2mQrfqCQ4Cr2/2023-Q1-Groups?node-id=2569%3A22489&t=sRTTyRhJHRhHQqYk-1

### LINKED ISSUE #2007: ux: calm engine redux
there is a clamor for calm.

>great to here! the calm engine in groups 1 made me realize how little control users had over what fought for their attention.
I can't go back.

-- `~nordus-mocwyl`

image

### LINKED ISSUE #2061: groups, gallery: can't delete on mobile, delete on desktop shows no spinner and hangs
- Be an admin of a group with a gallery channel that has stuff in it
- Attempt to delete gallery entry on mobile (I couldn't find out how)
- Attempt to delete same entry on desktop
- Observe it hang when you click delete with no spinner
- Hard refresh the page
- Observe that it is in fact deleted

### PR DESCRIPTION
**Pull request by jamesacklin**
Sweeping overhaul to application chrome.

- Unifies type, sizing, and spacing for lists of groups, channels, and messages between Groups and Talk for mobile viewports.
- Unifies type, sizing, and spacing for headers for mobile viewports on ancillary pages (Activity, Find Groups).
- Unifies type, sizing, and spacing for headers of all channels and content detail views (Curios, Threads, Notes) on mobile and desktop viewports.
- Implements reduced sort and filtering controls in Groups and Talk sidebars for desktop viewports.
- Improves the reliability of the "Back" button in the Note editor.
- Adds an "Edit" button to the Curio detail screen.
- Adds "sheet" dialogs for overflow of navigational items on mobile viewports for Groups.
- Adds the "Reconnecting" spinner to all requisite headers in Groups and Talk on mobile viewports.
- Adjusts the gutter of the Notebook list view on mobile viewports.
- Adjusts the size of skeleton loaders in a few places.
- Quiets the linter a bit.
- Makes group, channel, and message unread dots gray. Let's try it!
- Loads hinted webfonts to improve ligature appearance and Windows ClearType rendering.
- Eliminates surrounding backtics of `inline code` in Notebooks. 

Fixes #1746
Fixes #1186
Fixes #2061 
Fixes #1603 
Fixes #2007
Fixes #1293
Fixes #1190

### CODE REVIEW

**Comment by urcades** [comment]
I'm trying to run this PR locally to check it out, but for some reason groups never load:

Screenshot 2023-03-16 at 6 48 47 PM

I did manage to catch that there's a small issue with the sidebar row component butting up against the right edge of the sidebar in Talk:

Screenshot 2023-03-16 at 6 37 22 PM

**Comment by arthyn** [comment]
@urcades whatever you ship you have this pointed at needs to be synced to binnec I think

**Comment by jamesacklin** [comment]
Let me see if I can get some screenshots together.

**Comment by arthyn** [comment]
The text color on mobile seems too bright relative to desktop and many of the scrollbars seem to be cut in when they should butt up against the right side imo (or have only a very small gutter):
image

I think the icons look really small, if you're going to size it to `w-4 h-4` you need to use the small or 16 versions (might have to export a few). We probably should just default the sizes into all our icons, but alas.

Still looking through everything, I like how condensed we're getting (feel like mobile avatars could be as well) and sheet popup is great!

**Comment by jamesacklin** [comment]
Thanks -- I'll look at bringing the sidebars in more flush. Unfortunately Virtuoso doesn't like padding on itself so I'll shim the individual elements in. Such is life!

**Comment by jamesacklin** [comment]
To make everyone's lives easier, I've collected some screenshots. 

@urcades review at your leisure.

[2128-talk.zip](https://github.com/tloncorp/landscape-apps/files/11004645/2128-talk.zip)

Will follow up in a bit with Groups screenshots (many more states).

**Comment by urcades** [comment]
This is so good, the vast majority of the spacing/sizing updates to nav structures are looking perfect.

I have a few very small points of further aligning (on desktop updates alone) we can stand to make while we're updating everything:

First:

Section 2

In the comment sidebar for Gallery, and in a message thread, it looks like we're using two different styles for the "submit"/"send" button — we can stand to align on one of these. Perhaps we just stick with the iconographic/arrow button for sending, since it's a direction we've adopted on mobile for its smaller form-factor. We can make this button evenly square while we're here!

Next:

Section 3

While we don't need to cram the buttons and the search field inline with one another, we can simply just left-align the buttons for now. It'll make this screen a little more put-together.

Next:

Section 1

We should select one size for these "header" buttons across both screens. I'm happy for you to make a final call here, but I'm drawn the the larger variant here, as it seems to afford more space for search-like text fields.

I think this is all for now, the rest of the updates are looking really good.

**Review by urcades — CHANGES_REQUESTED** [review]
Forgot to include this status with the previous comments

**Comment by jamesacklin** [comment]
@urcades 🫡

image

image


image


image

**Review by urcades — APPROVED** [review]
🫡

**Comment by patosullivan** [comment]
fyi clicking on this caret down icon doesn't do anything: 
image

this is more of a style thing, but these notification buttons seem enormous to me:
image

in any case they should definitely be smaller on mobile, they're currently wider than the viewport:
localhost_3000_apps_groups_(iPhone 12 Pro) (1)

we also seem to be missing a bottom border on the channel header:
localhost_3000_apps_groups_(iPhone 12 Pro) (2)

**Comment by patosullivan** [comment]
Also, just noticed that there is a ton of top padding on mobile:

image

Intentional?

**Comment by jamesacklin** [comment]
@patosullivan No border is intentional: https://www.figma.com/file/sCFYLlAGjehlYXUkT2rarg/Product-Handoffs?node-id=2959-144731&t=PRub88aqUjlHLgYa-4

Will address the remainder, thank you

File: ui/src/logic/useSidebarSort.ts [hunk 1]
```diff
@@ -8,7 +8,7 @@ import useAllBriefs from './useAllBriefs';
 
 export const ALPHABETICAL = 'A → Z';
 export const DEFAULT = 'Arranged';
-export const RECENT = 'Recent';
```
Comment (patosullivan) [inline ui/src/logic/useSidebarSort.ts:11]: This change will mean that users who had the sidebar set to "Recent" before this update will need to manually set it again after the update. It will show "Recent Activity" as the selected sort mode, but it will actually be alphabetical. Probably best to just change the way this is displayed where it's being displayed, rather than with this change to the constant that we use in the logic/persistence.

Or, account for the old name being in the store and translate it to the new name.

File: ui/src/diary/diary-add-note.tsx [hunk 2]
```diff
@@ -126,32 +131,46 @@ export default function DiaryAddNote() {
       className="align-center w-full flex-1 bg-white"
       mainClass="overflow-y-auto"
       header={
-        <header className="flex h-full items-center justify-between border-b-2 border-gray-50 bg-white p-4">
+        <header
+          className={cn(
+            'flex items-center justify-between bg-white',
+            isMobile ? 'px-6 pt-10 pb-4' : 'border-b-2 border-gray-50 px-4 py-4'
```
Comment (patosullivan) [inline ui/src/diary/diary-add-note.tsx:137]: We should just use the tailwind breakpoint utilities here.

File: ui/src/dms/MultiDm.tsx [hunk 3]
```diff
@@ -57,45 +59,49 @@ export default function MultiDm() {
           isSelectingMessage ? (
             <MessageSelector />
           ) : (
-            <div className="flex h-full w-full items-center justify-between border-b-2 border-gray-50 p-2">
+            <div
+              className={cn(
+                'flex items-center justify-between bg-white',
+                isMobile
```
Comment (patosullivan) [inline ui/src/dms/MultiDm.tsx:65]: Same thing here.

File: ui/src/groups/FindGroups.tsx [hunk 4]
```diff
@@ -245,7 +244,7 @@ export default function FindGroups({ title }: ViewProps) {
                   isClearable={true}
                   isLoading={isPending}
                   hasPrompt={false}
-                  placeholder={''}
+                  placeholder={'e.g. ~nibset-napwyn/tlon'}
```
Comment (patosullivan) [inline ui/src/groups/FindGroups.tsx:247]: Great idea.

File: ui/src/groups/GroupSidebar/ChannelList.tsx [hunk 5]
```diff
@@ -45,31 +45,37 @@ interface ChannelListProps {
 
 export function ChannelSorter({ isMobile }: ChannelSorterProps) {
   const { sortFn, sortOptions, setSortFn } = useChannelSort();
+
+  function sortLabel() {
+    switch (sortFn) {
+      case 'Arranged':
+        return 'Arranged Channels';
+      case 'Recent Activity':
+        return 'Recent Activity';
```
Comment (patosullivan) [inline ui/src/groups/GroupSidebar/ChannelList.tsx:54]: Could just have the case set as "Recent" here and return "Recent Activity" to avoid the issue I mentioned.

**Review by patosullivan — CHANGES_REQUESTED** [review]
In general, looks great. The Sheet component is super nice.

A few nits here and I left some other comments on the PR.

File: ui/src/groups/GroupSidebar/ChannelList.tsx (hunk 5 above)
Comment (jamesacklin) [reply ui/src/groups/GroupSidebar/ChannelList.tsx:54]: Not sure what happened here, good catch.

**Review by arthyn — APPROVED** [review]
lgtm!

**Review by patosullivan — APPROVED** [review]
Looks great!
