### PR TITLE
gallery: don't show loading indicator if remote content is disabled.

### LINKED ISSUE #2376: gallery: hiding remote content kneecaps galleries
**Describe the bug, optionally with screenshots**
Turning off remote content wreaks lots of havoc in galleries. 

Issue 1: Images and other non-textual links are represented by an indefinite spinner in the Grid view and you are unable to click through to the detail view.

Issue 2: Images and other non-textual links occasionally show the root URL in the List view, as expected (but intermittent). You are able to click through to the detail view of these items, where the embedded content is rendered.

https://user-images.githubusercontent.com/748181/234268979-54021fc0-ef01-4197-85f8-cc44cfc21267.mov

**To Reproduce**
1. Hide remote content in your Landscape or Groups app settings.
2. Visit the "Our Bookshelf" channel in Tlon Local.
3. Flip between List and Grid views. 
4. In List view, click an item.

**Expected behavior**
- Any gallery item not linked to a web page should take on the same appearance and simply render the URL of the item (no spinner).
- I would expect to be able to click through to the detail view.
- The detail view should show the URL of the item, centered in the detail pane, similar to how we render links to web pages.

### PR DESCRIPTION
**Pull request by patosullivan**
Fixes #2376 by skipping the loading indicator if remote content is disabled.

Also renames/refactors "notEmbed" to "maybeEmbed" for better readability.

### CODE REVIEW

File: ui/src/heap/HeapBlock.tsx [hunk 1]
```diff
@@ -292,11 +292,11 @@ export default function HeapBlock({
   const flag = useRouteGroup();
   const isAdmin = useAmAdmin(flag);
   const canEdit = asRef ? false : isAdmin || window.our === curio.heart.author;
-  const notEmbed = isImage && isAudio && isText && isComment;
```
Comment (arthyn) [inline ui/src/heap/HeapBlock.tsx:295]: seems like this logic was faulty anyway, should have been ors right? your new logic is correct

**Review by arthyn — APPROVED** [review]
lgtm
