### PR TITLE
Groups: show private group join requested in group reference

### LINKED ISSUE #1081: Groups/References: Private group with join requested has no visual state in references
**Describe the bug, optionally with screenshots**
Clicking "request to join" on a chat reference to a private group results in the request sending, and appearing in the group list sidebar, but the chat reference seems to not have a "Requested" state, so it feels like nothing happened until you leave the group and return to the list of your groups (in talk, you can't tell at all!)

**To Reproduce**
1. Receive a reference to a private group your ship is not in
2. Click on "Request To Join"
3. Receive no visual feedback
4. Return to the "All Groups" sidebar or open the group info modal from the reference, see the join was requested
5. Return to the chat, observe no indication you've requested to join the group

**Expected behavior**
The "request to join" button becomes disabled, and the text is replaced with "Requested" (perhaps a "cancel" option appears next to it)

**Additional context:**
- planet
- self-hosted, digitalocean
- MacOS Chrome

### PR DESCRIPTION
**Pull request by patosullivan**
Fixes #1081

### CODE REVIEW

File: ui/src/components/References/GroupReference.tsx [hunk 1]
```diff
@@ -23,6 +26,19 @@ export default function GroupReference({ flag }: GroupReferenceProps) {
...
+    }
+    if (requested) {
+      return 'Join Requested';
+    }
+    if (privacy === 'private') {
+      return 'Request to Join';
+    }
+    return 'Join';
+  };
+
```
Comment (arthyn) [inline ui/src/components/References/GroupReference.tsx:41]: we already have this logic if you just use `button.text` from `useGroupJoin`, maybe we should it's language out for these though

Comment (patosullivan) [reply ui/src/components/References/GroupReference.tsx:41]: Thanks, missed that in useGroupJoin.

**Review by arthyn — APPROVED** [review]
lgtm
