### PR TITLE
Add a 'not' to fix backwards error logic

### LINKED ISSUE #2535: lure: in-group link block is broken
**Describe the bug, optionally with screenshots**
The Lure link for public groups I administrate are displaying as "Not enabled" or offline. The ship itself running the service is fine, according to @lukebuehler. 

My Landscape settings look like this:

image

A group I administrate but am not the host of:

image

A group I both administrate and host:

image
image

**To Reproduce**
1. Run the latest %groups, %talk, and %garden from the Tlon internal prerelease moon.
2. Navigate to a group you administrate that has Lure links enabled.
3. Attempt to copy the link.
4. Navigate to another group you administrate that does not have Lure links enabled.
5. Attempt to enable the link.

### PR DESCRIPTION
**Pull request by midsum-salrux**
Fixes #2535

### CODE REVIEW

File: ui/src/state/lure/lure.ts [hunk 1]
```diff
@@ -136,14 +136,14 @@ export const useLureState = create<LureState>(
...
         );
 
-        const enableAcked = await asyncWithDefault(
+        const enableAcked = !(await asyncWithDefault(
           () =>
             api.scry<boolean>({
               app: 'reel',
               path: `/outstanding-poke/${flag}`,
             }),
           true
```
Comment (arthyn) [inline ui/src/state/lure/lure.ts:145]: does the default need to change too or is it good?

Comment (midsum-salrux) [reply ui/src/state/lure/lure.ts:145]: The default is good

**Review by arthyn — APPROVED** [review]
lgtm
