### PR TITLE
heaps: fix posting and viewing app refs

### LINKED ISSUE #1321: refs: app ref seems to be broken

### PR DESCRIPTION
**Pull request by tomholford**
This change resolves #1321 by fixing a backend enjs key and several frontend reference issues.

image

https://user-images.githubusercontent.com/16504501/206242053-3ed44a93-2f54-4145-8f79-49b96fc2258a.mp4

TODO:

- [ ] styling of Open in Landscape button

### CODE REVIEW

File: ui/src/components/References/AppReference.tsx [hunk 1]
```diff
@@ -1,38 +1,31 @@
...
   const calm = useCalm();
+  const dark = useIsDark();
   const href = `/apps/grid/leap/search/${ship}/apps/${ship}/${deskId}`;
 
-  useEffect(() => {
-    if (!treaty && !isScrolling) {
-      useDocketState.getState().requestTreaty(ship, desk);
-    }
-  }, [treaty, ship, desk, isScrolling]);
-
```
Comment (arthyn) [inline ui/src/components/References/AppReference.tsx:26]: I think we still need this, otherwise it might not get fetched

**Review by arthyn — CHANGES_REQUESTED** [review]
One small change, everything else lgtm

**Review by arthyn — APPROVED** [review]
lgtm
