### PR TITLE
gallery: virtualize list, fetch new items at bottom

### LINKED ISSUE #1928: gallery: index only shows 50 posts
At the moment, we only fetch the first 50 posts in a Gallery channel. We should add pagination the same way we did to fix #1458.

Steps to reproduce:

1. Open a Gallery with >50 items (the "archive" channel in ~natnex-ronret/door-link is a good example)
2. See ~50 items

Expected behavior: paginate and lazy-load the next 50 curios.

### PR DESCRIPTION
**Pull request by patosullivan**
Fixes #1928 

Add VirtuosoGrid, fetch 50 new items when we reach the bottom of the current list. Had to create a fake curio and prepend it to the sortedCurio array (and then replace it) in order to get the NewCurioForm to render in the list.

https://user-images.githubusercontent.com/1221094/218874834-cf4f1e41-cb4b-4a86-b5e9-d335f5946c4e.mov

### CODE REVIEW

File: ui/src/heap/HeapChannel.tsx [hunk 1]
```diff
@@ -138,41 +140,90 @@ function HeapChannel({ title }: ViewProps) {
...
-          <div className="aspect-h-1 aspect-w-1">
-            <HeapBlock curio={curio} time={time.toString()} />
-          </div>
-        ) : (
-          <HeapRow key={time.toString()} curio={curio} time={time.toString()} />
-        )}
-      </div>
-    ),
-    [displayMode, navigateToDetail]
+    (i: number, curio: HeapCurio, time: bigInt.BigInteger) =>
```
Comment (arthyn) [inline ui/src/heap/HeapChannel.tsx:143]: I wonder if the `Header` component that virtuoso has would work here instead of having to fake it out

File: ui/src/heap/HeapChannel.tsx [hunk 2]
```diff
@@ -197,22 +248,18 @@ function HeapChannel({ title }: ViewProps) {
...
-      <div className="h-full overflow-y-scroll p-4">
-        <div
-          className={cn(
+      <div className="h-full p-4">
+        <VirtuosoGrid
+          data={canWrite ? sortedCurios : sortedCurios.slice(1)}
+          itemContent={(i, [time, curio]) => renderCurio(i, curio, time)}
+          computeItemKey={computeItemKey}
+          style={{ height: '100%', width: '100%', paddingTop: '1rem' }}
+          atBottomStateChange={loadOlderCurios}
```
Comment (arthyn) [inline ui/src/heap/HeapChannel.tsx:257]: this fires on both entry and leaving bottom

**Review by arthyn — APPROVED** [review]
lgtm, some things to maybe consider

File: ui/src/heap/HeapChannel.tsx (hunk 1 above)
Comment (patosullivan) [reply ui/src/heap/HeapChannel.tsx:143]: Tried it, it places it outside of the grid (above it).

File: ui/src/heap/HeapChannel.tsx (hunk 2 above)
Comment (patosullivan) [reply ui/src/heap/HeapChannel.tsx:272]: Good catch, fixed in latest commit.
