### PR TITLE
Wayfinding: fix mobile layout issues.

### LINKED ISSUE #1978: Wayfinding on mobile too narrow, doesn't scroll
**Describe the bug, optionally with screenshots**

On mobile click lower left ? bug. Select Wayfinding option. Wayfinding screen appears but is too narrow for available real estate and renders off screen without the ability to scroll. 

**Expected behavior**
Modal should use more real estate on a smaller screen and allow all content to be seen by scrolling. 

**Additional context:**
- self-hosted planet
- Chrome on iOS.

### PR DESCRIPTION
**Pull request by patosullivan**
Fixes #1978

### CODE REVIEW

File: ui/src/components/LandscapeWayfinding.tsx [hunk 1]
```diff
@@ -105,9 +105,11 @@ export default function LandscapeWayfinding() {
   return (
     <Dropdown.Root>
       <div
-        className={cn('fixed left-5 z-50', {
+        className={cn('fixed left-5', {
           'bottom-10': !isMobile || (isTalk && isMobile),
           'bottom-20': isMobile && !isTalk,
+          'z-40': showModal,
+          'z-50': !showModal,
```
Comment (arthyn) [inline ui/src/components/LandscapeWayfinding.tsx:112]: we could add another step instead of having to do this haha

**Review by arthyn — APPROVED** [review]
lgtm
