### PR TITLE
groups: add group home, assorted fixes

### LINKED ISSUE #1369: groups: text field in profile defaults to tiny
**Describe the bug, optionally with screenshots**
- Open profile
- Observe weirdly tiny bio text field
Screenshot 2022-12-08 at 4 54 38 PM

### LINKED ISSUE #2276: groups: clarify copy for Finding a Group
My friend who recently onboarded went to the Find Groups view to search for a vaporwave group:

PNG image

The placeholder does indicate that the host should be used:

image

But perhaps this is not intuitive for new users. So, we should consider clarifying the copy above the input, or adding some help text.

### PR DESCRIPTION
**Pull request by jamesacklin**
- Fixes #2554 by adjusting the in-group Activity feed to include the group summary, description, and an edit info button for admins. Also brings the notification list up to current design spec.
- Fixes #1369 by setting a height to the profile bio field somewhere around the max character count (1000).
- Fixes #2276 in Discover (ne Find) by adjusting the not-found error message and adding syntactic samples to the helper text above the field.
- Fixes an untracked bug brought about by #2492 where the Group Info nav item on mobile would not pop the group info dialog.

Preview of the group home for an admin (members don't see the "Edit Group Info" button):
image

---

Fixes LAND-235
Fixes LAND-277

### CODE REVIEW

File: ui/src/notifications/Notifications.tsx [hunk 1]
```diff
@@ -126,57 +129,41 @@ export default function Notifications({
...
       )}
-      <section className="h-full w-full overflow-y-scroll bg-gray-50">
+      <section className="flex h-full w-full flex-col space-y-6 overflow-y-scroll bg-gray-50 p-6">
         <Helmet>
-          <title>
-            {group
-              ? `All Notifications for ${group?.meta?.title} ${title}`
-              : title}
-          </title>
+          <title>{group ? `${group?.meta?.title} ${title}` : title}</title>
```
Comment (dantish) [inline ui/src/notifications/Notifications.tsx:134]: Maybe add some fallback value if `meta` is undefined to avoid displaying `undefined`? Or it's impossible that meta is not there?

**Review by dantish — APPROVED** [review]
LGTM👍

File: ui/src/notifications/Notifications.tsx [hunk 2]
```diff
@@ -98,11 +102,10 @@ export default function Notifications({
     <button
       disabled={isMarkReadPending || !hasUnreads}
       className={cn(
-        'whitespace-nowrap text-sm',
+        'small-button whitespace-nowrap text-sm',
         isMobile ? 'small-button' : 'button',
```
Comment (arthyn) [inline ui/src/notifications/Notifications.tsx:106]: if you want `small-button` all the time should it just be this?

```suggestion
        'small-button whitespace-nowrap text-sm',
```

**Review by arthyn — APPROVED** [review]
lgtm, just the one question
