### PR TITLE
notifications: fix mention links

### LINKED ISSUE #2263: groups: notifications for thread msgs open the msg as its own thread
Whenever I get mentioned in a message that is posted _in a thread_, this shows up correctly in my notifications.

However, clicking it opens the mention-message _as its own thread_, as opposed to opening in the context of the thread it was originally in.

I can respond in that "nested thread", but it won't be accessible in the groups chat interface through normal means. There is no "1 reply" indicator on the message in its original thread context.

What I really want is for clicking the notification to take me to the message _in its original context_, like it does correctly with top-level messages.

### PR DESCRIPTION
**Pull request by patosullivan**
fixes #2263 by opening up the thread and scrolling to the mention in question.

Also: for normal mentions (i.e., mentions in the main chat window), this routes the user to the mention within the chat window rather than prompting the user to start a new thread for the mention.

### CODE REVIEW

**Comment by arthyn** [comment]
does this work for all notifications? seems like it's only for chat-related ones

**Comment by patosullivan** [comment]
> does this work for all notifications? seems like it's only for chat-related ones

do we generate mention notifications for anything other than chats?

**Comment by patosullivan** [comment]
Looks like the only place we do it is line 1445 in app/chat.hoon

File: ui/src/logic/usePathFromHark.ts [hunk 1]
```diff
@@ -0,0 +1,45 @@
+import { udToDec } from '@urbit/api';
+import { useWritByFlagAndWritId } from '@/state/chat';
+import { Skein } from '@/types/hark';
+
+export default function usePathFromHark(bin: Skein, isMention: boolean) {
+  const writId = bin.top?.wer.split('/')[10];
```
Comment (arthyn) [inline ui/src/logic/usePathFromHark.ts:6]: Oh sorry I see now, I think it would be more clear if this early returned `wer` if it's not a mention above all the rest.

**Review by arthyn — CHANGES_REQUESTED** [review]

File: ui/src/logic/usePathFromHark.ts [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+    bin.top?.wer.split('/')[7]
+  }`;
+  const idWrit = `${ship}/${writId}`;
+  const replyToWrit = useWritByFlagAndWritId(channelFlag, idWrit || '', false)
+    ?.memo.replying;
+  const wer = bin.top?.wer;
+
+  if (!isMention) {
+    return wer;
+  }
```
Comment (arthyn) [inline ui/src/logic/usePathFromHark.ts:21]: I think this needs to be at the top otherwise this will error out when trying to reference specific segments like `[10]`

**Review by arthyn — CHANGES_REQUESTED** [review]

**Review by arthyn — APPROVED** [review]
I was wrong in my last comment, pushed a revert and gtg
