### PR TITLE
chat: fix issue where S3 urls would seem to persist as drafts

### LINKED ISSUE #1038: chat/s3: URL persists in draft
To reproduce:

1. Upload an image to a chat or DM using the + button, which inserts an image URL into the chat input.
2. Send the image to the chat.
3. Navigate away from the channel and come back.
4. Observe the URL persisting in the chat message input.
5. Navigate to _other_ chat channels and observe the URL persisting there.

Expected behavior:
Once sent, I should never see this URL again.

### PR DESCRIPTION
**Pull request by patosullivan**
Fixes #1038

### CODE REVIEW

File: ui/src/chat/ChatInput/ChatInput.tsx [hunk 1]
```diff
@@ -90,9 +96,9 @@ export default function ChatInput({
   const ship = replyingWrit && replyingWrit.memo.author;
   const isMobile = useIsMobile();
   const { loaded, hasCredentials, promptUpload } = useFileUpload();
-  const fileId = 'chat-input';
+  const fileId = useRef(`chat-input-${Math.floor(Math.random() * 1000000)}`);
```
Comment (tomholford) [inline ui/src/chat/ChatInput/ChatInput.tsx:99]: nit: could use `randomIntInRange` from `utils`

**Review by tomholford — APPROVED** [review]
Minor nit inline, not a merge-blocker. LGTM

File: ui/src/chat/ChatInput/ChatInput.tsx (hunk 1 above)
Comment (jamesacklin) [reply ui/src/chat/ChatInput/ChatInput.tsx:99]: (sickos) yes... ha ha ha... yes!
